Repository chingu-voyages/v46-tier2-team-14, pull requests merged in 2023-10, with the labels that each got.

#39 feat: theme toggle
  .eslintrc.cjs
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/css/fonts.css
  src/assets/css/reset.css
  src/assets/css/variables.css
  src/assets/fonts/Inter.ttf
  src/components/theme-toggle/ThemeToggle.tsx
  src/components/theme-toggle/theme-toggle.module.css
  src/context/ThemeContext.tsx
  src/hooks/useTheme.tsx
  src/index.css
  src/main.tsx
  vite.config.ts
Labels: fe

#41 Feature: Landing page with Header and Hero sections
  package-lock.json
  package.json
  src/App.tsx
  src/assets/css/fonts.css
  src/assets/css/variables.css
  src/components/layout/Layout.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/header.module.css
  src/components/layout/layout.module.css
  src/index.css
  src/main.tsx
  src/pages/home/Home.tsx
  src/pages/home/hero/Hero.tsx
  src/pages/home/hero/hero.module.css
  src/pages/home/home.module.css
Labels: fe

#45 added the route for recepie page
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Recipe.tsx
Labels: task, must_have, fe

#44 Add/skeleton component
  src/assets/css/variables.css
  src/components/skeleton/Skeleton.module.css
  src/components/skeleton/Skeleton.tsx
Labels: enhancement, nice_to_have, fe

#50 feat: add api config for detailed recipe
  .env.template
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/query-client.ts
  src/api/recipe.ts
  src/api/recipe.types.ts
  src/context/RecipeContext.tsx
  src/data/recipe.json
  src/data/recipes.json
  src/hooks/useRecipe.tsx
  src/hooks/useRecipeQuery.tsx
  src/main.tsx
  src/pages/Recipe.tsx
  src/pages/recipe/Recipe.tsx
  src/pages/recipe/recipe-ingredients/RecipeIngredients.tsx
  src/pages/recipe/recipe-instructions/RecipeInstructions.tsx
  src/pages/recipe/recipe-meta/RecipeMeta.tsx
  src/pages/recipe/recipe.module.css
Labels: fe

#49 Added Search Modal
  package-lock.json
  package.json
  src/hooks/useLocalStorage.tsx
  src/pages/home/hero/Hero.tsx
  src/pages/home/hero/hero.module.css
  src/pages/home/search/SearchModal.tsx
  src/pages/home/search/searchModal.module.css
  tsconfig.json
Labels: task, fe
